version: '3.8'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_laravel_web
    ports:
      - '8000:80'  # Mapea el puerto 5010 del host al puerto 80 del contenedor (Apache usa el puerto 80)
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=10.10.10.53
      - DB_PORT=5006
      - DB_DATABASE=elearning
      - DB_USERNAME=superuser
      - DB_PASSWORD=SE0ptCs58Zap
    volumes:
      - './elearning:/var/www/html'
      - './elearning/php.ini:/usr/local/etc/php/php.ini'  # Si necesitas personalizar la configuración de PHP


volumes:
  db_data:
