<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run()
    {
        DB::table('courses')->insert([
            [
                'id' => 1,
                'title_en' => 'Full-Stack Web Development Bootcamp: Basics to Advanced',
                'description_en' => 'Dive into the world of web development with a comprehensive bootcamp covering both front-end and back-end technologies. From HTML and CSS to server-side scripting, this course will equip you with the skills to build dynamic and interactive web applications.', 'course_category_id' => 5,
                'instructor_id' => 1,
                'typepayment_id' => 1,
                'price' => 5000.00,
                'old_price' => 9000.00,
                'subscription_price' => null,
                'full_course_subscription'=> 2500,
                'annual_subscription'=> null,
                'weekly_subscription'=> null,
                'daily_subscription'=> null,
                'start_from' => null,
                'duration' => 3,
                'lesson' => 35,
                'prerequisites_en' => 'Basic understanding of HTML and CSS; familiarity with programming concepts is beneficial but not required.', 'difficulty' => 'beginner',
                'course_code' => null,
                'image' => '1401704126972.jpg',
                'thumbnail_image' => '8191704126972.jpg',
                'thumbnail_video' => 'https://www.youtube.com/watch?v=lw6IVgb-omg',
                'tag' => 'popular',
                'status' => 2,
                'language' => 'en',
                'created_at' => '2023-11-26 03:30:17',
                'updated_at' => '2024-01-09 09:15:25',
                'deleted_at' => null
            ],
            [
            'id' => 2,
            'title_en' => 'Introduction to Data Science: From Basics to Advanced',
            'description_en' => 'Master the fundamentals of data science with a bootcamp that covers data analysis, machine learning, and data visualization techniques using Python.',
            'course_category_id' => 6,
            'instructor_id' => 2,
            'typepayment_id' => 1,
            'price' => 6000.00,
            'old_price' => 10000.00,
            'subscription_price' => null,
            'full_course_subscription'=> null,
            'annual_subscription'=> 500,
            'weekly_subscription'=> null,
            'daily_subscription'=> null,
            'start_from' => null,
            'duration' => 4,
            'lesson' => 40,
            'prerequisites_en' => 'Basic understanding of statistics and programming (preferably Python).',
            'difficulty' => 'intermediate',
            'course_code' => null,
            'image' => '4091704127086.jpg',
            'thumbnail_image' => '3521704127086.jpg',
            'thumbnail_video' => 'https://www.youtube.com/watch?v=DtGF52tN5dA',
            'tag' => 'popular',
            'status' => 2,
            'language' => 'en',
            'created_at' => '2023-11-28 04:15:20',
            'updated_at' => '2024-01-12 10:10:45',
            'deleted_at' => null
            ],
            [
                'id' => 3,
                'title_en' => 'Machine Learning with Python: A Comprehensive Guide',
                'description_en' => 'Learn the core concepts of machine learning, including regression, classification, clustering, and neural networks, with hands-on coding projects in Python.',
                'course_category_id' => 6,
                'instructor_id' => 3,
                'typepayment_id' => 2,
                'price' => 7500.00,
                'old_price' => 12000.00,
                'subscription_price' => null,
                'full_course_subscription'=> null,
                'annual_subscription'=> null,
                'weekly_subscription'=> 100,
                'daily_subscription'=> null,
                'start_from' => null,
                'duration' => 5,
                'lesson' => 50,
                'prerequisites_en' => 'Basic programming knowledge, familiarity with Python, and statistics.',
                'difficulty' => 'intermediate',
                'course_code' => null,
                'image' => '6891704127114.jpg',
                'thumbnail_image' => '6891704127114.jpg',
                'thumbnail_video' => 'https://www.youtube.com/watch?v=rmz9eG8vK2g',
                'tag' => 'featured',
                'status' => 2,
                'language' => 'en',
                'created_at' => '2023-11-30 02:45:10',
                'updated_at' => '2024-01-10 08:25:30',
                'deleted_at' => null
            ],
            [
                'id' => 4,
                'title_en' => 'Digital Marketing Essentials: Grow Your Business Online',
                'description_en' => 'Learn how to harness the power of digital marketing through SEO, social media strategies, content marketing, and paid ads.',
                'course_category_id' => 7,
                'instructor_id' => 1,
                'typepayment_id' => 3,
                'price' => 4000.00,
                'old_price' => 7000.00,
                'subscription_price' => null,
                'full_course_subscription'=> null,
                'annual_subscription'=> null,
                'weekly_subscription'=> null,
                'daily_subscription'=> 1,
                'start_from' => null,
                'duration' => 2,
                'lesson' => 25,
                'prerequisites_en' => 'No prior experience required, but basic knowledge of marketing concepts is helpful.',
                'difficulty' => 'beginner',
                'course_code' => null,
                'image' => '6781704127193.jpg',
                'thumbnail_image' => '7821704127193.jpg',
                'thumbnail_video' => 'https://www.youtube.com/watch?v=FbqBrj8gK5w',
                'tag' => 'upcoming',
                'status' => 2,
                'language' => 'en',
                'created_at' => '2023-12-01 05:25:30',
                'updated_at' => '2024-01-05 11:00:55',
                'deleted_at' => null
            ]
        ]);
    }
}
