<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
            ['id' => 185, 'role_id' => 1, 'name' => 'user.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 186, 'role_id' => 1, 'name' => 'user.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 187, 'role_id' => 1, 'name' => 'user.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 188, 'role_id' => 1, 'name' => 'user.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 189, 'role_id' => 1, 'name' => 'user.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 190, 'role_id' => 1, 'name' => 'role.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 191, 'role_id' => 1, 'name' => 'role.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 192, 'role_id' => 1, 'name' => 'role.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 193, 'role_id' => 1, 'name' => 'role.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 194, 'role_id' => 1, 'name' => 'role.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 195, 'role_id' => 1, 'name' => 'student.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 196, 'role_id' => 1, 'name' => 'student.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 197, 'role_id' => 1, 'name' => 'student.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 198, 'role_id' => 1, 'name' => 'student.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 199, 'role_id' => 1, 'name' => 'student.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 200, 'role_id' => 1, 'name' => 'instructor.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 201, 'role_id' => 1, 'name' => 'instructor.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 202, 'role_id' => 1, 'name' => 'instructor.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 203, 'role_id' => 1, 'name' => 'instructor.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 204, 'role_id' => 1, 'name' => 'instructor.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 205, 'role_id' => 1, 'name' => 'courseCategory.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 206, 'role_id' => 1, 'name' => 'courseCategory.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 207, 'role_id' => 1, 'name' => 'courseCategory.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 208, 'role_id' => 1, 'name' => 'courseCategory.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 209, 'role_id' => 1, 'name' => 'courseCategory.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 210, 'role_id' => 1, 'name' => 'course.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 211, 'role_id' => 1, 'name' => 'course.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 212, 'role_id' => 1, 'name' => 'course.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 213, 'role_id' => 1, 'name' => 'course.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 214, 'role_id' => 1, 'name' => 'course.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 215, 'role_id' => 1, 'name' => 'material.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 216, 'role_id' => 1, 'name' => 'material.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 217, 'role_id' => 1, 'name' => 'material.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 218, 'role_id' => 1, 'name' => 'material.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 219, 'role_id' => 1, 'name' => 'material.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 220, 'role_id' => 1, 'name' => 'quiz.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 221, 'role_id' => 1, 'name' => 'quiz.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 222, 'role_id' => 1, 'name' => 'quiz.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 223, 'role_id' => 1, 'name' => 'quiz.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 224, 'role_id' => 1, 'name' => 'quiz.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 225, 'role_id' => 1, 'name' => 'question.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 226, 'role_id' => 1, 'name' => 'question.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 227, 'role_id' => 1, 'name' => 'question.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 228, 'role_id' => 1, 'name' => 'question.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 229, 'role_id' => 1, 'name' => 'question.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 230, 'role_id' => 1, 'name' => 'option.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 231, 'role_id' => 1, 'name' => 'option.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 232, 'role_id' => 1, 'name' => 'option.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 233, 'role_id' => 1, 'name' => 'option.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 234, 'role_id' => 1, 'name' => 'option.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 235, 'role_id' => 1, 'name' => 'studentPaymentPlan.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 236, 'role_id' => 1, 'name' => 'studentPaymentPlan.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 237, 'role_id' => 1, 'name' => 'studentPaymentPlan.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 238, 'role_id' => 1, 'name' => 'studentPaymentPlan.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 239, 'role_id' => 1, 'name' => 'studentPaymentPlan.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 240, 'role_id' => 1, 'name' => 'settings.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 241, 'role_id' => 1, 'name' => 'settings.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 242, 'role_id' => 1, 'name' => 'review.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 243, 'role_id' => 1, 'name' => 'review.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 244, 'role_id' => 1, 'name' => 'review.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 245, 'role_id' => 1, 'name' => 'discussion.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 246, 'role_id' => 1, 'name' => 'discussion.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 247, 'role_id' => 1, 'name' => 'discussion.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 248, 'role_id' => 1, 'name' => 'discussion.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 249, 'role_id' => 1, 'name' => 'discussion.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 250, 'role_id' => 1, 'name' => 'message.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 251, 'role_id' => 1, 'name' => 'message.create','created_at' => now(), 'updated_at' => now()],
            ['id' => 252, 'role_id' => 1, 'name' => 'message.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 253, 'role_id' => 1, 'name' => 'message.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 254, 'role_id' => 1, 'name' => 'message.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 255, 'role_id' => 1, 'name' => 'permission.list', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 256, 'role_id' => 2, 'name' => 'student.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 257, 'role_id' => 2, 'name' => 'student.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 258, 'role_id' => 2, 'name' => 'student.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 259, 'role_id' => 2, 'name' => 'student.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 260, 'role_id' => 2, 'name' => 'student.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 261, 'role_id' => 2, 'name' => 'studentPaymentPlan.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 262, 'role_id' => 2, 'name' => 'studentPaymentPlan.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 263, 'role_id' => 2, 'name' => 'studentPaymentPlan.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 264, 'role_id' => 2, 'name' => 'studentPaymentPlan.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 265, 'role_id' => 2, 'name' => 'studentPaymentPlan.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 266, 'role_id' => 2, 'name' => 'user.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 267, 'role_id' => 2, 'name' => 'user.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 268, 'role_id' => 2, 'name' => 'user.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 269, 'role_id' => 2, 'name' => 'user.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 270, 'role_id' => 2, 'name' => 'user.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 271, 'role_id' => 3, 'name' => 'user.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 272, 'role_id' => 3, 'name' => 'role.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 273, 'role_id' => 3, 'name' => 'student.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 274, 'role_id' => 3, 'name' => 'instructor.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 275, 'role_id' => 3, 'name' => 'courseCategory.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 276, 'role_id' => 3, 'name' => 'course.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 277, 'role_id' => 3, 'name' => 'course.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 278, 'role_id' => 3, 'name' => 'course.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 279, 'role_id' => 3, 'name' => 'course.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 280, 'role_id' => 3, 'name' => 'course.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 281, 'role_id' => 3, 'name' => 'studentPaymentPlan.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 282, 'role_id' => 3, 'name' => 'studentPaymentPlan.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 283, 'role_id' => 3, 'name' => 'studentPaymentPlan.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 284, 'role_id' => 3, 'name' => 'studentPaymentPlan.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 285, 'role_id' => 2, 'name' => 'quiz.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 286, 'role_id' => 2, 'name' => 'question.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 287, 'role_id' => 2, 'name' => 'question.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 288, 'role_id' => 2, 'name' => 'question.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 289, 'role_id' => 2, 'name' => 'question.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 290, 'role_id' => 2, 'name' => 'question.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 291, 'role_id' => 2, 'name' => 'option.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 292, 'role_id' => 2, 'name' => 'option.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 293, 'role_id' => 2, 'name' => 'option.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 294, 'role_id' => 2, 'name' => 'option.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 295, 'role_id' => 2, 'name' => 'option.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 296, 'role_id' => 2, 'name' => 'answer.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 297, 'role_id' => 2, 'name' => 'answer.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 298, 'role_id' => 2, 'name' => 'answer.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 299, 'role_id' => 2, 'name' => 'answer.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 300, 'role_id' => 2, 'name' => 'answer.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 301, 'role_id' => 2, 'name' => 'review.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 302, 'role_id' => 2, 'name' => 'review.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 303, 'role_id' => 2, 'name' => 'review.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 304, 'role_id' => 2, 'name' => 'review.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 305, 'role_id' => 2, 'name' => 'review.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 306, 'role_id' => 2, 'name' => 'discussion.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 307, 'role_id' => 2, 'name' => 'discussion.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 308, 'role_id' => 2, 'name' => 'discussion.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 309, 'role_id' => 2, 'name' => 'discussion.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 310, 'role_id' => 2, 'name' => 'discussion.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 311, 'role_id' => 2, 'name' => 'message.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 312, 'role_id' => 2, 'name' => 'message.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 313, 'role_id' => 2, 'name' => 'message.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 314, 'role_id' => 2, 'name' => 'message.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 315, 'role_id' => 2, 'name' => 'message.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 345, 'role_id' => 3, 'name' => 'user.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 346, 'role_id' => 3, 'name' => 'user.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 347, 'role_id' => 3, 'name' => 'user.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 348, 'role_id' => 3, 'name' => 'user.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 349, 'role_id' => 3, 'name' => 'user.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 350, 'role_id' => 3, 'name' => 'courseCategory.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 351, 'role_id' => 3, 'name' => 'courseCategory.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 352, 'role_id' => 3, 'name' => 'courseCategory.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 353, 'role_id' => 3, 'name' => 'courseCategory.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 354, 'role_id' => 3, 'name' => 'course.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 355, 'role_id' => 3, 'name' => 'course.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 356, 'role_id' => 3, 'name' => 'course.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 357, 'role_id' => 3, 'name' => 'course.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 358, 'role_id' => 3, 'name' => 'course.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 359, 'role_id' => 3, 'name' => 'material.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 360, 'role_id' => 3, 'name' => 'material.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 361, 'role_id' => 3, 'name' => 'material.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 362, 'role_id' => 3, 'name' => 'material.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 363, 'role_id' => 3, 'name' => 'material.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 364, 'role_id' => 3, 'name' => 'lesson.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 365, 'role_id' => 3, 'name' => 'lesson.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 366, 'role_id' => 3, 'name' => 'lesson.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 367, 'role_id' => 3, 'name' => 'lesson.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 368, 'role_id' => 3, 'name' => 'lesson.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 369, 'role_id' => 3, 'name' => 'coupon.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 370, 'role_id' => 3, 'name' => 'coupon.create', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 371, 'role_id' => 3, 'name' => 'coupon.show', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 372, 'role_id' => 3, 'name' => 'coupon.edit', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 373, 'role_id' => 3, 'name' => 'coupon.destroy', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 374, 'role_id' => 3, 'name' => 'enrollment.index', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 375, 'role_id' => 3, 'name' => 'student.create', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
