<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Elias',
                'middlename' => 'Augusto',
                'lastname' => 'Chavarria',
                'lastname2' => 'Bouchabki',
                'email' => 'eliasito97@gmail.com',
                'contact_en' => '+8801300025229',
                'country' => NULL,
                'role_id' => 1,
                'password' => '$2y$12$RDPYtmf4JJwoQ4sEMuVYse6kg.Xnv1vcJ86sZhT63uaL5vrMje69W',
                'language' => 'en',
                'image' => '7741704114296.png',
                'full_access' => 1,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2024-01-01 06:47:43',
                'updated_at' => '2024-01-01 07:04:57',
                'deleted_at' => NULL,
                'instructor_id' => NULL,
            ],
            [
                'id' => 2,
                'name' => 'Gonzalo',
                'middlename' => NULL,
                'lastname' => 'Dante',
                'lastname2' => NULL,
                'email' => 'Gonzalo@gmail.com',
                'contact_en' => '3453534521',
                'country' => NULL,
                'role_id' => 3,
                'password' => '$2y$12$CgGd2qfI/1nRHDyzYBUq3.nuw/vWV.e9hP/Ze6T6tEzpgng.Dyl6m',
                'language' => 'en',
                'image' => 'Instructor_Asadullah Galib_310.jpg',
                'full_access' => 0,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2024-01-01 07:49:40',
                'updated_at' => '2024-02-21 14:20:18',
                'deleted_at' => NULL,
                'instructor_id' => NULL,
            ],
            [
                'id' => 3,
                'name' => 'Eduardo',
                'middlename' => NULL,
                'lastname' => 'Alcazar',
                'lastname2' => NULL,
                'email' => 'Eduardo@gmail.com',
                'contact_en' => '675664644',
                'country' => NULL,
                'role_id' => 3,
                'password' => '$2y$12$1l18cpPxU4M2zZgMxECs6ezwQKGM/ton5GsztDIiFz0keVvmVsX4O',
                'language' => 'en',
                'image' => 'Instructor_Joshim Uddin_155.jpg',
                'full_access' => 0,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2024-01-01 07:50:08',
                'updated_at' => '2024-02-21 14:19:51',
                'deleted_at' => NULL,
                'instructor_id' => NULL,
            ],
            [
                'id' => 4,
                'name' => 'Ruben',
                'middlename' => NULL,
                'lastname' => 'Chavarria',
                'lastname2' => NULL,
                'email' => 'Ruben@gmail.com',
                'contact_en' => '3218974218',
                'country' => NULL,
                'role_id' => 3,
                'password' => '$2y$12$slth2axx..G1Nz.3jFSa4eHOfBzJybSrjSY3ocZCOQSx10KEcdqtO',
                'language' => 'en',
                'image' => 'Instructor_Raihan Sazzad_662.jpg',
                'full_access' => 0,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2024-01-01 07:50:18',
                'updated_at' => '2024-02-21 14:18:57',
                'deleted_at' => NULL,
                'instructor_id' => NULL,
            ],
            [
                'id' => 5,
                'name' => 'Daniela',
                'middlename' => NULL,
                'lastname' => 'Peramas',
                'lastname2' => NULL,
                'email' => 'Daniela@gmail.com',
                'contact_en' => '801300029',
                'country' => NULL,
                'role_id' => 3,
                'password' => '$2y$12$ua2TYVVOxnQWxa2RFnD1euGL8rRUwzFZ2m/uWOw8V/pFfNI3K8Qxa',
                'language' => 'en',
                'image' => 'Instructor_Thouhidul Islam_766.jpg',
                'full_access' => 0,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2024-01-01 07:50:28',
                'updated_at' => '2024-02-21 14:17:19',
                'deleted_at' => NULL,
                'instructor_id' => NULL,
            ],
            [
                'id' => 6,
                'name' => 'Oscar',
                'middlename' => NULL,
                'lastname' => 'Terrazas',
                'lastname2' => 'Morales',
                'email' => 'Oscar@gmail.com',
                'contact_en' => '01828543453',
                'country' => NULL,
                'role_id' => 3,
                'password' => '$2y$12$uTGQ75wrj/r/2wZgWe8tVeetckNkgGaqMczxzGhRTbxLWvAfpADp6',
                'language' => 'en',
                'image' => 'Instructor_Burhan Uddin Fuad_137.jpg',
                'full_access' => 0,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2024-01-01 07:50:43',
                'updated_at' => '2024-02-21 14:15:37',
                'deleted_at' => NULL,
                'instructor_id' => 1,
            ],
            [
            'id' => 7,
            'name' => 'Monica',
            'middlename' => 'Jorge',
            'lastname' => 'Lens',
            'lastname2' => 'Bouchabki',
            'contact_en' => '5456612',
            'country' => null,
            'email' => 'Monica@gmail.com',
            'role_id' => 3,
            'password' => '$2y$12$uTGQ75wrj/r/2wZgWe8tVeetckNkgGaqMczxzGhRTbxLWvAfpADp6',
            'language' => 'en',
            'image' => 'Instructor_Thouhidul Islam_766.jpg',
            'full_access' => 0,
            'status' => 1,
            'remember_token' => NULL,
            'created_at' => '2024-01-01 07:50:43',
            'updated_at' => '2024-02-21 14:15:37',
            'deleted_at' => NULL,
            'instructor_id' => 2,
             ],
            [
                'id' => 8,
                'name' => 'Tarek',
                'middlename' => 'Gonzalo',
                'lastname' => 'Chavarria',
                'lastname2' => 'Bouchabki',
                'contact_en' => '22222222',
                'country' => null,
                'email' => 'Tarek@gmail.com',
                'role_id' => 3,
                'password' => '$2y$12$uTGQ75wrj/r/2wZgWe8tVeetckNkgGaqMczxzGhRTbxLWvAfpADp6',
                'language' => 'en',
                'image' => 'Instructor_Raihan Sazzad_662.jpg',
                'full_access' => 0,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2024-01-01 07:50:43',
                'updated_at' => '2024-02-21 14:15:37',
                'deleted_at' => NULL,
                'instructor_id' => 3,
            ]
        ]);
    }
}
